### ISSUE TITLE
pid not displaying (maybe because of sudo?)

### ISSUE THREAD

**Issue by jeanlucthumm** [FMotalleb/nu_plugin_port_list#2]
```nu
~/Code/lobe-chat-db on ☁️  jeanlucthumm@gmail.com 
❯ sudo lsof -i :5432
COMMAND    PID USER FD   TYPE DEVICE SIZE/OFF NODE NAME
docker-pr 4405 root 4u  IPv4   7142      0t0  TCP *:postgresql (LISTEN)
docker-pr 4412 root 4u  IPv6  14461      0t0  TCP *:postgresql (LISTEN)

~/Code/lobe-chat-db on ☁️  jeanlucthumm@gmail.com 
❯ port list | where local_port == 5432
╭───┬──────┬────────────┬───────────────┬────────────┬────────────────┬─────────────┬────────┬─────╮
│ # │ type │ ip_version │ local_address │ local_port │ remote_address │ remote_port │ state  │ pid │
├───┼──────┼────────────┼───────────────┼────────────┼────────────────┼─────────────┼────────┼─────┤
│ 0 │ tcp  │          4 │ 0.0.0.0       │       5432 │ 0.0.0.0        │           0 │ LISTEN │     │
│ 1 │ tcp  │          6 │ ::            │       5432 │ ::             │           0 │ LISTEN │     │
╰───┴──────┴────────────┴───────────────┴────────────┴────────────────┴─────────────┴────────┴─────╯
```

Not getting pid, but I assume this is because the command doesn't have root access, right?

If that's the case, what's the recommended way to use this plugin? I'm pretty sure nushell plugins aren't installed for all users, so a sudo nu instance won't have it unless I install it there too

**Comment by fmotalleb** [comment]
You're correct. I'll look into whether it's possible to use `capadd` instead of `sudo`.

**Comment by fmotalleb** [comment]
To solve this issue, you can give your plugin specific Linux capabilities, so it can access network and process information without needing root privileges. Just run this command:

```bash
sudo setcap 'cap_net_admin,cap_sys_ptrace,cap_dac_read_search=ep' (Plugin bin path)
```

### Here's what each capability does:

1. **`cap_net_admin`**:  
   - Lets your plugin handle network-related tasks like configuring interfaces or getting more detailed info about the network.

2. **`cap_sys_ptrace`**:  
   - Allows the plugin to inspect and interact with other running processes, which is crucial for gathering `PID`s and doing process-level debugging or monitoring.

3. **`cap_dac_read_search`**:  
   - Allows the plugin to bypass permission restrictions, giving it the ability to read protected files and directories, like those in `/proc`, without requiring root access.

### The `=ep` part means:

- **`e` (Effective)**: The capability is active when the program runs.
- **`p` (Permitted)**: The program has permission to use the capabilities.

By doing this, your plugin can get the necessary access without needing to be run as `sudo`.

**Comment by fmotalleb** [comment]
While this persists after reboot, caps will be removed after the Plugin re-install and needs to be added again, I'll add this script to nupm build script
